apiVersion: v1
kind: Service
metadata:
  name: opspanzu-service
spec:
  selector:
    app: opspanzu-webcontent-complete
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer
